<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body style="background-color: balck; padding: 5em;">
    <h1>RICHIESTA INFORMAZIONI</h1>
    <hr>
    <p>
        Richiesta informazioni da %s (NickName).
        <br>
        MESSAGGIO:
        <br>
        %s
        <br>
    </p>
    <br>
    <p>
        Copyright Simone Tempesta 2023
    </p>
    
</body>
</html>